### ISSUE TITLE
📝Agenda Item Proposal - Motion to create mission/value statement working group

### ISSUE THREAD

**Issue by thomasrayner** [markekraus/psharp#3]
# Background

Discussion in Discord regarding language features, user stories, and other such items are currently done in an ad hoc way without much of a unified paradigm. I believe there is a need for a unified vision and/or mission statement, and an initial series of user stories to define the target audience and user base for the to-be-built language.

# Motion

Move to form a working group of at least 3 and no more than 5 foundation members (led by 1) to deliver:
* A mission/vision statement for the to-be-built language
* At least 5 and no more than 20 initial user stories to define target user base for the to-be-built language (ex: As a `programmer` I wish to `write code in a language my ops folks on the help desk understand` in order to `increase our opportunities for collaboration`)

# Notes

@markekraus, please apply a `agenda-item` label 😁 

# Updates

* Removed item from motion to create mission/vision statement for the foundation as a whole, since that is going to be covered by the Incorporation Working Group.

**Comment by markekraus** [comment]
I should have specified, but Mission/Vision is part of Articles of Incorporation. Generally, those need to be included to limit the scope of business, especially for a 501(c)(3). Obviously, these would be voted on by the foundation members.

**Comment by thomasrayner** [comment]
Perhaps this proposed motion can just be re-scoped to the user stories.

**Comment by vexx32** [comment]
I still think that mission/vision for the language is valuable. I get the impression that the Articles of Incorporation will have a mission/vision statement that is for the Foundation itself, which will be related to but not necessarily define the mission/vision statement for the language itself.

**Comment by markekraus** [comment]
@vexx32 that's my thinking too. Vision and Mission of the foundation for the articles of incorporation, vision mission of the language separate.

**Comment by thomasrayner** [comment]
Is it proper for me to edit the original post here to reflect this change in scope? Or does this discussion capture it adequately?

**Comment by markekraus** [comment]
I say update it

**Comment by thomasrayner** [comment]
Done. I'm going to guess that the endorsements provided already don't need to be re-applied since the spirit of the agenda item is still consistent with it's original form.

**Comment by markekraus** [comment]
I would recommend sponsors confirm their sponsorship in comments. Using updoots is not great, IMO.

**Comment by vexx32** [comment]
I'm for this one, both are things which would give us a good place to start with language design. 🙂 

EDIT: If it's not clear, I'll happily sponsor this 👍

**Comment by thomasrayner** [comment]
> I would recommend sponsors confirm their sponsorship in comments. Using updoots is not great, IMO.

Agreed that updoots aren't great, but I worry about the requirement of 5 sponsors when folks don't appear to be super great at staying on top of GitHub notifs, and the process is still really new...

**Comment by markekraus** [comment]
If you want something sponsored, you have to do some leg work to get people to sponsor it. Reach out to them on discord or whatever and get them to come here and comment. I never intended this to be 0 effort and don't think what works in reality.

This is the order of operations in my head:

1. Draft a motion
2. Politic some people into sponsoring it with you
3. Work with sponsors on the wording
4. Freeze the wording
5. Submit to parliamentarian before the deadline
6. Motion is presented
7. Sponsors of the motion attest
8. Discussion/debate
9. Vote

So, yes, there is some work on the part of a person who is putting forth a motion to drive it to a successful vote. That's expected.

**Comment by markekraus** [comment]
Also, you can have 3 sponsors for things that only require a simple majority.

https://github.com/markekraus/psharp/blob/main/foundation-by-laws.md#agenda-items-and-sponsorship

> Sponsors of Agenda Items will determine the correct majority (Simple or Large) to pass the Agenda Item. Agenda Items requiring **a simple majority must have a minimum of three** sponsors. Agenda Items requiring a large majority must have a minimum of five sponsors.

**Comment by adilio** [comment]
I am just putting in writing that I endorse/sponsor the updated version of @thomasrayner's motion / agenda item above. 👍🏼

**Comment by Windos** [comment]
👍

...

Consider me a sponsor for this agenda item

**Comment by markekraus** [comment]
The motion was discussed, voted on, and passed during the 2021-06-05 General Session. The resolution has been documented here https://github.com/markekraus/psharp/blob/main/resolutions/20210605-01.md
